"""
Queries SQL para a aba "Rede Hoje" (fonte: NTW_OP.MUNICIPIOS_FECHAMENTO).
"""

BASE_CTE_TEMPLATE = """
WITH BASE AS (
    SELECT
        IBGE,
        UF,
        MUNICIPIO,
        PRESENCA,
        PRESENCA_5G,
        PRESENCA_4G,
        PRESENCA_3G,
        PRESENCA_2G,
        BANDA_2G_MHZ,
        BANDA_3G_MHZ,
        BANDA_4G_MHZ,
        BANDA_5G_MHZ,
        MES_DIV_2G,
        MES_DIV_3G,
        MES_DIV_4G,
        MES_DIV_5G
    FROM NTW_OP.MUNICIPIOS_FECHAMENTO
    WHERE TRUNC(DT_CARGA) = (
        SELECT TRUNC(MAX(DT_CARGA))
        FROM NTW_OP.MUNICIPIOS_FECHAMENTO
    )
    {uf_filter}
    {municipio_filter}
    {tecnologia_filter}
)
"""


KPIS_TEMPLATE = """
SELECT
    COUNT(*) AS total_municipios,
    NVL(SUM(PRESENCA), 0) AS municipios_cobertos,
    NVL(SUM(PRESENCA_5G), 0) AS municipios_5g,
    NVL(SUM(PRESENCA_4G), 0) AS municipios_4g,
    NVL(SUM(PRESENCA_3G), 0) AS municipios_3g,
    NVL(SUM(PRESENCA_2G), 0) AS municipios_2g
FROM BASE
"""


VENN_TEMPLATE = """
SELECT
    SUM(CASE WHEN PRESENCA_2G=1 AND PRESENCA_3G=0 AND PRESENCA_5G=0 THEN 1 ELSE 0 END) AS only_2g,
    SUM(CASE WHEN PRESENCA_2G=0 AND PRESENCA_3G=1 AND PRESENCA_5G=0 THEN 1 ELSE 0 END) AS only_3g,
    SUM(CASE WHEN PRESENCA_2G=0 AND PRESENCA_3G=0 AND PRESENCA_5G=1 THEN 1 ELSE 0 END) AS only_5g,
    SUM(CASE WHEN PRESENCA_2G=1 AND PRESENCA_3G=1 AND PRESENCA_5G=0 THEN 1 ELSE 0 END) AS inter_2g_3g,
    SUM(CASE WHEN PRESENCA_2G=1 AND PRESENCA_3G=0 AND PRESENCA_5G=1 THEN 1 ELSE 0 END) AS inter_2g_5g,
    SUM(CASE WHEN PRESENCA_2G=0 AND PRESENCA_3G=1 AND PRESENCA_5G=1 THEN 1 ELSE 0 END) AS inter_3g_5g,
    SUM(CASE WHEN PRESENCA_2G=1 AND PRESENCA_3G=1 AND PRESENCA_5G=1 THEN 1 ELSE 0 END) AS inter_all,
    NVL(SUM(PRESENCA_2G), 0) AS total_2g,
    NVL(SUM(PRESENCA_3G), 0) AS total_3g,
    NVL(SUM(PRESENCA_5G), 0) AS total_5g,
    COUNT(*) AS total_municipios
FROM BASE
"""


TABLE_TEMPLATE = """
SELECT
    UF,
    MUNICIPIO,
    PRESENCA,
    PRESENCA_5G,
    PRESENCA_4G,
    PRESENCA_3G,
    PRESENCA_2G
FROM BASE
ORDER BY UF, MUNICIPIO
"""


UFS_QUERY = """
SELECT DISTINCT UF
FROM NTW_OP.MUNICIPIOS_FECHAMENTO
WHERE TRUNC(DT_CARGA) = (
    SELECT TRUNC(MAX(DT_CARGA))
    FROM NTW_OP.MUNICIPIOS_FECHAMENTO
)
ORDER BY UF
"""


MUNICIPIOS_SEARCH_QUERY = """
SELECT DISTINCT MUNICIPIO, UF
FROM NTW_OP.MUNICIPIOS_FECHAMENTO
WHERE TRUNC(DT_CARGA) = (
    SELECT TRUNC(MAX(DT_CARGA))
    FROM NTW_OP.MUNICIPIOS_FECHAMENTO
)
AND UPPER(MUNICIPIO) LIKE UPPER(:q)
{uf_filter}
ORDER BY MUNICIPIO
FETCH FIRST 100 ROWS ONLY
"""


FREQUENCIES_TEMPLATE = """
SELECT TEC, BANDA, COUNT(DISTINCT IBGE) AS QTD
FROM (
    SELECT
        b.IBGE,
        '2G' AS TEC,
        TRIM(REGEXP_SUBSTR(REGEXP_REPLACE(b.BANDA_2G_MHZ, '\\s*\\([^)]*\\)', ''),
                           '[^/]+', 1, LEVELS.LVL)) AS BANDA
    FROM BASE b
    CROSS JOIN (
        SELECT LEVEL AS LVL FROM DUAL CONNECT BY LEVEL <= 10
    ) LEVELS
    WHERE b.PRESENCA_2G = 1
      AND b.BANDA_2G_MHZ IS NOT NULL
      AND REGEXP_SUBSTR(b.BANDA_2G_MHZ, '[^/]+', 1, LEVELS.LVL) IS NOT NULL

    UNION ALL

    SELECT
        b.IBGE,
        '3G' AS TEC,
        TRIM(REGEXP_SUBSTR(REGEXP_REPLACE(b.BANDA_3G_MHZ, '\\s*\\([^)]*\\)', ''),
                           '[^/]+', 1, LEVELS.LVL)) AS BANDA
    FROM BASE b
    CROSS JOIN (
        SELECT LEVEL AS LVL FROM DUAL CONNECT BY LEVEL <= 10
    ) LEVELS
    WHERE b.PRESENCA_3G = 1
      AND b.BANDA_3G_MHZ IS NOT NULL
      AND REGEXP_SUBSTR(b.BANDA_3G_MHZ, '[^/]+', 1, LEVELS.LVL) IS NOT NULL

    UNION ALL

    SELECT
        b.IBGE,
        '4G' AS TEC,
        TRIM(REGEXP_SUBSTR(REGEXP_REPLACE(b.BANDA_4G_MHZ, '\\s*\\([^)]*\\)', ''),
                           '[^/]+', 1, LEVELS.LVL)) AS BANDA
    FROM BASE b
    CROSS JOIN (
        SELECT LEVEL AS LVL FROM DUAL CONNECT BY LEVEL <= 10
    ) LEVELS
    WHERE b.PRESENCA_4G = 1
      AND b.BANDA_4G_MHZ IS NOT NULL
      AND REGEXP_SUBSTR(b.BANDA_4G_MHZ, '[^/]+', 1, LEVELS.LVL) IS NOT NULL

    UNION ALL

    SELECT
        b.IBGE,
        '5G' AS TEC,
        TRIM(REGEXP_SUBSTR(REGEXP_REPLACE(b.BANDA_5G_MHZ, '\\s*\\([^)]*\\)', ''),
                           '[^/]+', 1, LEVELS.LVL)) AS BANDA
    FROM BASE b
    CROSS JOIN (
        SELECT LEVEL AS LVL FROM DUAL CONNECT BY LEVEL <= 10
    ) LEVELS
    WHERE b.PRESENCA_5G = 1
      AND b.BANDA_5G_MHZ IS NOT NULL
      AND REGEXP_SUBSTR(b.BANDA_5G_MHZ, '[^/]+', 1, LEVELS.LVL) IS NOT NULL
)
WHERE BANDA IS NOT NULL
GROUP BY TEC, BANDA
ORDER BY
    CASE TEC WHEN '2G' THEN 1 WHEN '3G' THEN 2 WHEN '4G' THEN 3 WHEN '5G' THEN 4 END,
    CASE
        WHEN REGEXP_LIKE(BANDA, '^[0-9]+$') THEN TO_NUMBER(BANDA)
        ELSE 999999
    END,
    BANDA
"""


TIMESERIES_TEMPLATE = """
SELECT TEC, PERIODO, QTD
FROM (
    SELECT
        '2G' AS TEC,
        TRUNC(MES_DIV_2G, 'MM') AS PERIODO,
        COUNT(DISTINCT IBGE) AS QTD
    FROM BASE
    WHERE MES_DIV_2G IS NOT NULL
    GROUP BY TRUNC(MES_DIV_2G, 'MM')

    UNION ALL

    SELECT
        '3G' AS TEC,
        TRUNC(MES_DIV_3G, 'MM') AS PERIODO,
        COUNT(DISTINCT IBGE) AS QTD
    FROM BASE
    WHERE MES_DIV_3G IS NOT NULL
    GROUP BY TRUNC(MES_DIV_3G, 'MM')

    UNION ALL

    SELECT
        '4G' AS TEC,
        TRUNC(MES_DIV_4G, 'MM') AS PERIODO,
        COUNT(DISTINCT IBGE) AS QTD
    FROM BASE
    WHERE MES_DIV_4G IS NOT NULL
    GROUP BY TRUNC(MES_DIV_4G, 'MM')

    UNION ALL

    SELECT
        '5G' AS TEC,
        TRUNC(MES_DIV_5G, 'MM') AS PERIODO,
        COUNT(DISTINCT IBGE) AS QTD
    FROM BASE
    WHERE MES_DIV_5G IS NOT NULL
    GROUP BY TRUNC(MES_DIV_5G, 'MM')
)
ORDER BY TEC, PERIODO
"""